### PR TITLE
Fix build failure and move apt install step to its own action

### PR DESCRIPTION
**Pull request by MetRonnie**
Fix ``convert-im6.q16: unable to read font `helvetica'`` error on nightly & deploy workflows

### CODE REVIEW

**Comment by oliver-sanders** [comment]
I'm guessing the last fix only worked on certain versions of Ubuntu?

**Review by oliver-sanders — APPROVED** [review]
Works on Ubuntu 20.

**Comment by oliver-sanders** [comment]
If we hit any more problems can consider installing `imagemagick` from apt or building the stack in Conda.

**Comment by MetRonnie** [comment]
> I'm guessing the last fix only worked on certain versions of Ubuntu?

I think it worked for any current version, but it was only implemented for the test workflow, not nightly or deploy

**Pull request merged**
