### PR TITLE
setup: bump cylc-sphinx-extensions to 1.3.1+

### PR DESCRIPTION
**Pull request by oliver-sanders**
Fixes bug documenting Cylc configurations caused by a nested section inside a meta section.

### CODE REVIEW

**Comment by oliver-sanders** [comment]
Need to wait a little while before 1.3.1 arrives in the pip cache.

**Review by MetRonnie — APPROVED** [review]

**Comment by oliver-sanders** [comment]
rerunning nightly

**Comment by oliver-sanders** [comment]
passed

**Comment by MetRonnie** [comment]
Time to deploy docs for 8.0b3?

**Comment by oliver-sanders** [comment]
Not yet, still working through the release process.

**Pull request merged**
