### PR TITLE
Update introduction.rst

### PR DESCRIPTION
**Pull request by damienfrancois**
Typo in command to copy some files to work with into a new workflow

### CODE REVIEW

**Comment by oliver-sanders** [comment]
Thanks @damienfrancois 

Please can you add your name to the list of [code-contributors](https://github.com/cylc/cylc-doc/blob/master/CONTRIBUTING.md#code-contributors).

**Review by hjoliver — APPROVED** [review]
Thanks @damienfrancois

**Comment by hjoliver** [comment]
Oops, sorry missed @oliver-sanders comment on adding @damienfrancois to the code contributors list (in CONTRIBUTING.md).

@damienfrancois can you do that with another PR please?

**Comment by damienfrancois** [comment]
This is just a typo correction, but ok.. please see https://github.com/cylc/cylc-doc/pull/441

**Pull request merged**
