### PR TITLE
8.2.x sync

### PR DESCRIPTION
**Pull request by oliver-sanders**
**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.

### CODE REVIEW

**Comment by wxtim** [comment]
Still failing on the sphinx build 😞

**Comment by oliver-sanders** [comment]
I think it'll pass when the jps 2 one goes in

**Comment by oliver-sanders** [comment]
To make tests pass, either fix hieroglyph :( or disable it :(

**Comment by oliver-sanders** [comment]
Failing on linkcheck, but I think everything before has passed.

**Comment by oliver-sanders** [comment]
(merged in upstream/8.2.x again)

**Comment by oliver-sanders** [comment]
That's fixed the spurious reference errors, but linkcheck is still unhappy.

**Comment by oliver-sanders** [comment]
(another merge)

**Comment by oliver-sanders** [comment]
PASSED!

**Pull request merged**
