### PR TITLE
Uniform dependencies section in suite.rc

### PR DESCRIPTION
**Pull request by matthewrmshin**
Companion for cylc/cylc-flow#3191 - cycling and non-cycling suites now have
uniform level in the dependencies section.

### CODE REVIEW

**Comment by hjoliver** [comment]
(Will review this after/with cylc/cylc-flow/pull/2935)

**Comment by matthewrmshin** [comment]
Re-based.

**Comment by oliver-sanders** [comment]
The Cylc Tutorial is in this repo now as well. Do we want to attempt that after https://github.com/cylc/cylc-doc/issues/40 or now?

**Comment by hjoliver** [comment]
I guess that's mainly a question for @matthewrmshin. (The order doesn't really matter, except that it affects who does the work).

**Comment by matthewrmshin** [comment]
Merge both in. Open new issue.

**Pull request merged**
