### PR TITLE
make: Add sphinx-autobuild support

### PR DESCRIPTION
**Pull request by oliver-sanders**
Makes working with Sphinx much, much easier.

```console
$ make watch
```

Once you do this the docs will rebuild (incrementally where possible) whenever. Your browser will automatically refresh when this happens 🎉 😁 🥳 🕺!

There is also a `make watch-cylc` target which listens for changes in the `cylc-flow`, `cylc-uiserver` & `cylc-rose` repos. Note this performs a non-incremental build which is substantially slower.

### CODE REVIEW

**Comment by oliver-sanders** [comment]
(haven't tested it on NFS, sadly it might not work there)

**Review by MetRonnie — APPROVED** [review]
Tested on NFS

**Comment by oliver-sanders** [comment]
Great! Might be worth investigating what library they are using to detect filesystem events at some point (NFS is tricky for this stuff). If it's efficient it could provide us with a more efficient, incremental `cylc scan` which would be great.

**Review by hjoliver — APPROVED** [review]
Nice.

**Pull request merged**
