### PR TITLE
xtriggers: autodocument template variables

### PR DESCRIPTION
**Pull request by oliver-sanders**
* Sibling: https://github.com/cylc/cylc-flow/pull/4777
* Requires: https://github.com/cylc/cylc-doc/pull/422 (will fail until this is merged)

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.

### CODE REVIEW

**Review by hjoliver — APPROVED** [review]

**Review by wxtim — APPROVED** [review]

**Comment by wxtim** [comment]
@oliver-sanders  - do you know why the tests were failing?

**Comment by oliver-sanders** [comment]
Yep, needed the PR marked as required in the OP merged.

**Comment by wxtim** [comment]
> Yep, needed the PR marked as required in the OP merged.

I think that I remember that PR had been merged when I kicked the CI yesterday - but I've kicked it again. If it passes I will merge...

**Comment by oliver-sanders** [comment]
I don't think kicking CI has the desired effect in this case (the merge commit doesn't change for reruns?), rebased.

**Pull request merged**
