### PR TITLE
actions: split test workflow

### PR DESCRIPTION
**Pull request by oliver-sanders**
* Run the tutorial suite tests in another workflow.
* Move from pycodestyle -> flake8

### CODE REVIEW

**Review by MetRonnie — APPROVED** [review]
Not sure why the tests are failing on GH Actions, passing locally for me

**Comment by oliver-sanders** [comment]
Hmmm, perhaps a recent merge?

**Comment by oliver-sanders** [comment]
Ok, that's really strange

```
 <unknown>:783:undefined label: namespace-names
```

https://github.com/cylc/cylc-doc/pull/263/checks?check_run_id=3046264826#step:10:200

But the `namespace-names` target was defined on another branch net yet merged:

https://github.com/cylc/cylc-doc/pull/258/files#diff-735487292549209ce34cf25d7492b05179907d18f36335e9627dbeca57821d93R26

**Comment by MetRonnie** [comment]
Test failures due to https://github.com/cylc/cylc-flow/pull/4290 and because #258 hasn't been merged yet

(I'm resolving the comments about it above)

**Comment by oliver-sanders** [comment]
Merged now.

**Comment by oliver-sanders** [comment]
sibling PR merged, rebased, test passing (ignore tut workflow for now), merging.

**Pull request merged**
