### PR TITLE
GH Actions: Install correct branches of other libs

### PR DESCRIPTION
**Pull request by MetRonnie**
**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.

### CODE REVIEW

**Review by wxtim — COMMENTED** [review]
Looks sane - how can I test it?

**Comment by oliver-sanders** [comment]
Can trigger a manual run via "workflow dispatch".

**Comment by oliver-sanders** [comment]
Seems legit, I think currently the other repos are relying on the version of cylc-flow in the `setup.cfg` files resulting in `pip uninstall cylc-flow=<master-from-gh>` / `pip install=<bugfix-from-pypi>`.

**Comment by oliver-sanders** [comment]
Will need a procedure of some form to remind us to bump these versions up. Suggest adding a bullet point to the release steps on cylc-admin.

**Comment by oliver-sanders** [comment]
Will need a follow-on to set the tags for 8.1 releases.

**Pull request merged**
