### PR TITLE
8.0.x -> master

### PR DESCRIPTION
**Pull request by MetRonnie**
Remember to do a normal merge instead of squash

### CODE REVIEW

**Comment by MetRonnie** [comment]
Test failure due to linkcheck, fixed in https://github.com/cylc/cylc-rose/pull/201

**Comment by datamel** [comment]
Does the linkfix needs to be on master rather than 1.1.x?

**Comment by MetRonnie** [comment]
Yes, https://github.com/cylc/cylc-rose/pull/202

**Comment by MetRonnie** [comment]
@datamel Ready to review

**Review by wxtim — APPROVED** [review]

**Pull request merged**
