### PR TITLE
fix version indicator

### PR DESCRIPTION
**Pull request by oliver-sanders**

### CODE REVIEW

**Review by kinow — APPROVED** [review]
I had seen this one when clicking to test the links in the new README, good catch! :+1:

**Comment by kinow** [comment]
BTW, build broken, but doesn't seem to be related to this change

```
2020-10-14T10:34:19.6556305Z Warning, treated as error:
2020-10-14T10:34:19.6558234Z autodoc: failed to import class 'Priv' from module 'cylc.flow.network.authorisation'; the following exception was raised:
2020-10-14T10:34:19.6559616Z Traceback (most recent call last):
2020-10-14T10:34:19.6561291Z   File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/sphinx/util/inspect.py", line 325, in safe_getattr
2020-10-14T10:34:19.6562802Z     return getattr(obj, name, *defargs)
2020-10-14T10:34:19.6564493Z AttributeError: module 'cylc.flow.network.authorisation' has no attribute 'Priv'
```

**Comment by kinow** [comment]
(I think one review will do, but will leave open so @oliver-sanders can take a look at the build status)

**Comment by oliver-sanders** [comment]
I've deployed a manual patch to the 8.0a2 docs.

**Comment by oliver-sanders** [comment]
The docs build is failing awaiting a docs change to match a Cylc Flow change - https://github.com/cylc/cylc-flow/pull/3845#issuecomment-702280534

**Comment by kinow** [comment]
Yup! New version displayed correctly :+1: 

image

**Pull request merged**
