### PR TITLE
Add .mailmap and add shortlog check action

### PR DESCRIPTION
**Pull request by datamel**
Closes https://github.com/cylc/cylc-doc/issues/437

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.

### CODE REVIEW

**Comment by oliver-sanders** [comment]
Might as well do #437 along with this because it validates the mailmap against the contributor list.

**Comment by hjoliver** [comment]
@datamel - I pushed a commit to fix up the `.mailmap` syntax.

Before:
```console
$ shortlog -se
    17  Bruno Kinoshita <bruno.kinoshita@niwa.co.nz>
    22  Bruno P. Kinoshita <kinow@users.noreply.github.com>
     1  David Matthews <david.matthews@metoffice.gov.uk>
   138  Hilary James Oliver <hilary.j.oliver@gmail.com>
     2  Hilary Oliver <h.oliver@niwa.co.nz>
     1  Hilary Oliver <hilary.j.oliver@gmail.com>
    14  Matt Shin <matthew.shin@metoffice.gov.uk>
    60  Mel Hall <37735232+datamel@users.noreply.github.com>
   249  Oliver Sanders <oliver.sanders@metoffice.gov.uk>
   104  Ronnie Dutta <61982285+MetRonnie@users.noreply.github.com>
     5  Sadie Bartholomew <30274190+sadielbartholomew@users.noreply.github.com>
     7  Sadie Bartholomew <sadie.bartholomew@metoffice.gov.uk>
   185  Tim Pillinger <26465611+wxtim@users.noreply.github.com>
     1  Tim Pillinger <tim.pillinger@metoffice.gov.uk>
     6  Tomek Trzeciak <TomekTrzeciak@users.noreply.github.com>
     3  TomekTrzeciak <tomasz.trzeciak@metoffice.gov.uk>
    11  WXTIM <26465611+wxtim@users.noreply.github.com>
     3  github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
```
After:
```console
$ git shortlog -se
    39  Bruno Kinoshita <kinow@apache.org>
     1  David Matthews <david.matthews@metoffice.gov.uk>
   142  Hilary Oliver <hilary.j.oliver@gmail.com>
    14  Matt Shin <matthew.shin@metoffice.gov.uk>
    60  Mel Hall <mel.hall@metoffice.gov.uk>
   249  Oliver Sanders <oliver.sanders@metoffice.gov.uk>
   104  Ronnie Dutta <ronnie.dutta@metoffice.gov.uk>
    12  Sadie Bartholomew <sadie.bartholomew@metoffice.gov.uk>
   197  Tim Pillinger <tim.pillinger@metoffice.gov.uk>
     9  Tomek Trzeciak <tomasz.trzeciak@metoffice.gov.uk>
     3  github-actions[bot] <github-actions@no-reply.github.com>
```

**Review by wxtim — APPROVED** [review]

**Review by oliver-sanders — APPROVED** [review]

**Comment by datamel** [comment]
> @datamel - I pushed a commit to fix up the `.mailmap` syntax.
> 
Apologies I accidentally forced pushed this away. I have redone a similar change so the short log is the same as your one. There are missing contributors whom I will add in brackets as in cylc-flow.

**Comment by oliver-sanders** [comment]
The action is failing, I think it's failing to load the contributors from the file.

https://github.com/cylc/cylc-doc/runs/5717244964?check_suite_focus=true

**Comment by oliver-sanders** [comment]
Ah, that'd do it.

**Pull request merged**
