### PR TITLE
Restructure

### PR DESCRIPTION
**Pull request by oliver-sanders**
Quick change to rationalise the documentation structure to this:

* Installation
* Introduction
* Tutorial
* User Guide
* Suite Design Guide
* Reference
* Glossary

Content needs reviewing (obviously), and the landing pages for the user-guide and reference pages need writing etc.

Note: One section is missing "Quick Start".

Also remove the old CLI documentation generation, we need to re-implement this once the CLI has settled a little.

### CODE REVIEW

**Comment by hjoliver** [comment]
> Also remove the old CLI documentation generation, we need to re-implement this once the CLI has settled a little.

Not entirely convinced that I should ever have put that in.  It doubles the size of the user guide, when all you need to do is type `cylc help` etc.

**Comment by oliver-sanders** [comment]
It's fine to have it in (when auto-documented) so long as it's buried in the reference material.

It's nice for:

* Internal references (e.g. visualise your suite using `cylc graph`)
* Integrity checking (e.g. run your suite using `rose suite-run` => Error: reference "rose suite-run" not found)
* Searching (e.g. `search: graph a suite`).
* People who don't have Cylc installed but are digging through the command reference anyway (e.g. my on my Phone)

**Comment by oliver-sanders** [comment]
> currently failing on Travis CI?

Pre-existing failure in Cylc Flow docstring, fixed in https://github.com/cylc/cylc-flow/pull/3496

**Comment by hjoliver** [comment]
(merged the fix)

**Comment by oliver-sanders** [comment]
Now a broken URL.

(first person to update the docs after a period gets all the bugs, hmmm, nightly builds, ...)

**Comment by hjoliver** [comment]
I'll just merge this, we'll be doing a lot of work on this before the release anyway.

**Pull request merged**
